import React, { useEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { AnimatePresence, motion, useInView, useReducedMotion } from 'framer-motion';
import { ArrowDownRight, ArrowUpRight, BrainCircuit, Check, ChevronRight, CircleDot, Download, Mail, Menu, Network, ShieldCheck, Sparkles, X, Zap } from 'lucide-react';
import './styles.css';

const resumeHref = '/assets/durgesh-unde-resume.pdf';

const research = [
  {
    id: '01', date: 'August 2023', type: 'Research Study', title: 'Enhancing Cybersecurity with Machine Learning-Based Threat Detection',
    short: 'A study of intelligent threat detection systems that use supervised and unsupervised learning to identify malicious patterns, anomalies, and evolving attack vectors.',
    tags: ['Cybersecurity', 'Threat detection', 'Random Forest', 'Anomaly detection'], accent: 'cyan', pdf: '/research/enhancing-cybersecurity-threat-detection.pdf',
    question: 'How can machine learning strengthen threat detection beyond static, signature-based security?',
    objectives: ['Improve detection accuracy for known and unknown threats', 'Reduce false alarms and alert fatigue', 'Explore automated response and escalation', 'Evaluate supervised and unsupervised ML approaches'],
    method: 'Literature-led analysis of software-level threat detection, using network traffic, system logs, user behaviour, publicly available datasets, and discussion of practical enterprise implementation.',
    findings: 'The study concludes that machine-learning-based approaches can improve detection accuracy, reduce false positives, and support automated threat response when integrated with operational security infrastructure.',
    takeaway: 'Adaptive pattern recognition gives security teams a path beyond predefined signatures — while data, compute, and deployment context still matter.',
  },
  {
    id: '02', date: 'February 2024', type: 'Individual Research Report', title: 'AI in Healthcare Diagnostics: Beyond Human Accuracy',
    short: 'An exploration of deep learning, medical imaging, clinical decision support, and the conditions required for responsible, explainable diagnostic AI.',
    tags: ['Healthcare AI', 'Deep learning', 'Medical imaging', 'Explainability'], accent: 'amber', pdf: '/research/ai-healthcare-diagnostics.pdf',
    question: 'Where can AI-assisted diagnostics exceed average human performance, and what must accompany that capability?',
    objectives: ['Trace the evolution from rule-based systems to deep learning', 'Examine imaging, oncology, pathology, and clinical decision support', 'Consider bias, data quality, explainability, and regulation', 'Map future directions such as multimodal and federated learning'],
    method: 'Independent synthesis of the technical evolution and practical implications of AI diagnostics, with attention to deep neural networks, CNNs, foundation models, clinical workflow, and human oversight.',
    findings: 'The report presents targeted diagnostic tasks where AI can match or exceed average human performance, while emphasising that generalisation, trust, validation, fairness, and clinical integration determine real-world value.',
    takeaway: 'The strongest model is not the whole solution: reliable diagnostic AI depends on high-quality data, transparent reasoning, and collaborative clinical use.',
  },
  {
    id: '03', date: 'No date stated', type: 'Formal Academic Investigation', title: 'Fake News Detection Using Machine Learning Techniques',
    short: 'A methodology for identifying misinformation in text through NLP feature extraction, comparative modelling, and a hybrid CNN + SVM detection approach.',
    tags: ['Misinformation', 'NLP', 'CNN + SVM', 'Text classification'], accent: 'violet', pdf: '/research/fake-news-detection-ml.pdf',
    question: 'How can machine learning distinguish legitimate news from fabricated content at the speed and scale of online platforms?',
    objectives: ['Develop robust models for text classification', 'Compare content, source, and propagation feature sets', 'Benchmark accuracy, precision, recall, and F1-score', 'Propose a scalable framework for content credibility'],
    method: 'A reproducible pipeline covering data acquisition, preprocessing, TF-IDF or embeddings, deterministic splits, cross-validation, comparative model training, and evaluation on public text datasets.',
    findings: 'The paper reports that a hybrid approach combining CNN deep feature extraction with traditional SVM classification outperforms single-method systems in the presented framework.',
    takeaway: 'Detection quality is inseparable from semantic context, evolving deception, representative labels, and careful handling of false positives.',
  },
  {
    id: '04', date: 'December 2024', type: 'Independent Research Presentation', title: 'AI in Climate Change Prediction and Environmental Sustainability',
    short: 'A visual research presentation on AI for climate prediction, renewable energy optimisation, resource management, ecological conservation, and equitable deployment.',
    tags: ['Climate AI', 'Neural networks', 'Sustainability', 'Equity'], accent: 'green', pdf: '/research/ai-climate-change-sustainability.pdf',
    question: 'How can computational intelligence support climate action while remaining accessible, fair, and environmentally responsible?',
    objectives: ['Explore neural networks and deep learning for atmospheric and ocean modelling', 'Survey renewable energy, resource, and conservation applications', 'Critically examine compute, access, and algorithmic bias', 'Assess future implications for climate policy'],
    method: 'Structured research presentation synthesising climate science context, predictive modelling approaches, sustainability applications, ethical challenges, and future outlook.',
    findings: 'The presentation positions AI as a powerful tool for prediction and resource optimisation, while identifying computational cost, data accessibility, bias, and equitable deployment as central constraints.',
    takeaway: 'Climate intelligence is valuable only when its benefits can reach the communities most exposed to climate risk.',
  },
  {
    id: '05', date: 'September 2025', type: 'Independent Research', title: 'The Evolution of Generative AI Models: From Text to General Intelligence',
    short: 'A deep dive into the progression from transformer-based text generation to multimodal systems, reasoning, contextual awareness, and the still-theoretical horizon of AGI.',
    tags: ['Generative AI', 'Transformers', 'Multimodal', 'Human-AI collaboration'], accent: 'rose', pdf: '/research/evolution-generative-ai-models.pdf',
    question: 'What changes as generative models move from fluent text production toward broader, more general capabilities?',
    objectives: ['Trace the evolution from GPT-2 and GPT-3 to modern foundation models', 'Explain the transformer architecture and emergent capabilities', 'Compare task-specific ML with general-purpose generative systems', 'Explore safety, governance, and the human role in future AI'],
    method: 'Independent research synthesis spanning model history, architecture, multimodal systems, reasoning, regulation, projected milestones, and human-AI collaboration.',
    findings: 'The paper describes a staged evolution toward broader generalisation and multimodal reasoning, while clearly treating full AGI as aspirational and not yet achieved.',
    takeaway: 'Capability growth is inseparable from context, governance, and the uniquely human judgement that guides how systems are used.',
  },
];

const experience = [
  { period: 'Aug 2026 — Present', role: 'AI Data Annotation & Evaluation Contractor', company: 'Innodata India Pvt. Ltd.', current: true, body: 'Hands-on work across AI/ML training data annotation, content moderation, grounding and reference-expression tasks, and quality-focused evaluation workflows.', bullets: ['Dense-structured grounding, CUA-general grounding, and high-resolution reference-expression annotation', 'Evaluate AI-generated outputs for accuracy, contextual relevance, consistency, and overall quality', 'Apply project-specific guidelines, linguistic and semantic review, data quality standards, AHT, and benchmarks', 'Manage task activity, quality control, timelines, and project reporting'] },
  { period: '2026 — July 2026', role: 'AI Training & Data Annotation Contributor', company: 'Outlier AI', body: 'Contributed structured human feedback to AI training and model evaluation projects, with a focus on consistent labelling and output quality.', bullets: ['Evaluated AI-generated outputs against detailed quality criteria', 'Image annotation, data labelling, and content quality assessment', 'Speech and voice data collection using English, Hindi, and Marathi spoken prompts'] },
];

const skills = {
  'AI & Machine Learning': ['AI Data Annotation', 'AI Model Evaluation', 'AI Evaluation & RLHF', 'Human Feedback / Human-in-the-Loop Evaluation', 'AI Training Data', 'Grounding Annotation', 'Reference-Expression Annotation', 'Content Quality Assessment', 'Data Quality Assurance', 'AI Speech & Voice Training', 'Research & Academic Writing'],
  'Programming & Technical': ['Python (Scripting & Libraries)', 'HTML', 'CSS', 'JavaScript', 'Version Control (Git)'],
  'Professional': ['Attention to Detail', 'Analytical Thinking', 'Problem Solving', 'Written Communication', 'Adaptability', 'Time Management'],
  'Languages': ['English (Advanced)', 'Hindi (Advanced)', 'Marathi (Advanced)'],
};

function Reveal({ children, className = '', delay = 0, y = 24 }) {
  const reduce = useReducedMotion();
  const ref = useRef(null); const inView = useInView(ref, { once: true, margin: '-80px' });
  return <motion.div ref={ref} className={className} initial={reduce ? false : { opacity: 0, y }} animate={inView || reduce ? { opacity: 1, y: 0 } : {}} transition={{ duration: .7, delay, ease: [0.16, 1, 0.3, 1] }}>{children}</motion.div>;
}

function Mark() { return <div className="mark" aria-hidden="true"><span /><span /><span /></div>; }

function Header({ onNavigate }) {
  const [open, setOpen] = useState(false); const [scrolled, setScrolled] = useState(false);
  useEffect(() => { const fn = () => setScrolled(window.scrollY > 24); window.addEventListener('scroll', fn); return () => window.removeEventListener('scroll', fn); }, []);
  const nav = ['about', 'experience', 'skills', 'research', 'projects', 'contact'];
  const go = (id) => { setOpen(false); onNavigate(id); };
  return <header className={`site-header ${scrolled ? 'scrolled' : ''}`}><div className="nav-wrap"><a className="brand" href="#top" onClick={(e) => { e.preventDefault(); go('top'); }}><Mark /><span>DURGESH<br /><em>UNDE</em></span></a><nav className={open ? 'open' : ''}>{nav.map((item, i) => <a key={item} href={`#${item}`} onClick={(e) => { e.preventDefault(); go(item); }}><span>0{i + 1}</span>{item[0].toUpperCase() + item.slice(1)}</a>)}</nav><div className="nav-actions"><a className="nav-resume" href={resumeHref} download="Durgesh-Unde-Resume.pdf">Resume <Download size={14} /></a><button className="menu-button" aria-label={open ? 'Close menu' : 'Open menu'} aria-expanded={open} onClick={() => setOpen(v => !v)}>{open ? <X size={20} /> : <Menu size={20} />}</button></div></div></header>;
}

function Hero({ onNavigate }) {
  return <section className="hero" id="top"><div className="hero-grid" /><div className="hero-glow glow-one" /><div className="hero-glow glow-two" /><div className="hero-orbit orbit-one" /><div className="hero-orbit orbit-two" /><div className="hero-content page-width"><Reveal><div className="eyebrow"><span className="status-dot" /> Open to thoughtful AI work <span className="eyebrow-line" /></div></Reveal><Reveal delay={.05}><div className="hero-name">DURGESH UNDE</div><div className="hero-role">AI Training &amp; Evaluation <span>/</span> Data Annotation <span>/</span> AI Model Evaluation</div></Reveal><Reveal delay={.08}><h1>Training the<br /><span>signal</span> inside AI.</h1></Reveal><Reveal delay={.16}><p className="hero-copy">I work at the human and data layer of AI - annotating training data, evaluating model outputs, and building the quality signals that help systems become more useful.</p></Reveal><Reveal delay={.24}><div className="hero-actions"><button className="button button-primary" onClick={() => onNavigate('experience')}>Explore my work <ArrowDownRight size={17} /></button><button className="button button-quiet" onClick={() => onNavigate('research')}>View research <ArrowUpRight size={17} /></button><a className="button button-ghost" href={resumeHref} download="Durgesh-Unde-Resume.pdf">Download resume <Download size={16} /></a></div></Reveal><Reveal delay={.3}><div className="hero-foot"><div><span className="mini-label">FOCUS</span><strong>AI training data - evaluation - human feedback</strong></div><div className="scroll-note"><span className="scroll-line" /> Scroll to explore</div></div></Reveal></div><div className="signal-panel" aria-hidden="true"><div className="signal-label">LIVE / HUMAN-IN-THE-LOOP</div><div className="signal-canvas"><div className="signal-ring ring-a" /><div className="signal-ring ring-b" /><div className="signal-core"><BrainCircuit size={28} /><span>01</span></div>{Array.from({ length: 14 }).map((_, i) => <i className={`node node-${i}`} key={i} />)}<svg viewBox="0 0 500 500"><path d="M90 148 C180 80 230 220 304 150 S430 130 416 286 290 420 192 350 98 310 90 148" /><path d="M56 270 C170 220 208 330 274 274 S365 170 444 252" /><path d="M156 62 C120 184 220 224 182 440" /></svg></div><div className="signal-meta"><span>annotation</span><span>evaluation</span><span>quality</span></div></div></section>;
}

function SectionIntro({ eyebrow, title, copy, id }) { return <div className="section-intro" id={id}><div className="eyebrow"><span className="eyebrow-index">/</span>{eyebrow}</div><h2 dangerouslySetInnerHTML={{ __html: title }} />{copy && <p>{copy}</p>}</div>; }

function About() { return <section className="about section page-width" id="about"><Reveal><SectionIntro eyebrow="01 / PROFILE" title={'The work behind <em>better models.</em>'} copy="Durgesh is an emerging AI professional working across the practical, human side of machine learning: the data, judgments, and quality systems that shape how models learn." /></Reveal><div className="about-layout"><Reveal delay={.08} className="about-note"><div className="editorial-number">01</div><p>My focus is the layer where human understanding becomes machine-readable signal — from grounding and reference-expression annotation to output review, multilingual voice data, and structured feedback.</p><span className="line-accent" /></Reveal><Reveal delay={.16} className="keyword-field"><div className="keyword-card keyword-main"><Sparkles size={18} /><span>Human-in-the-loop<br /><strong>evaluation</strong></span></div>{['AI training data', 'grounding annotation', 'content quality', 'RLHF', 'semantic review', 'research writing'].map((x, i) => <span className={`keyword keyword-${i}`} key={x}>{x}</span>)}</Reveal></div></section>; }

function Experience() { const [active, setActive] = useState(0); return <section className="experience section page-width" id="experience"><Reveal><SectionIntro eyebrow="02 / EXPERIENCE" title={'Close to the <em>signal.</em>'} copy="A practical track record across annotation, evaluation, data labelling, and quality assurance — with work that keeps the model and the real world connected." /></Reveal><div className="experience-layout"><div className="timeline-list">{experience.map((item, i) => <button className={`timeline-trigger ${active === i ? 'active' : ''}`} key={item.company} onClick={() => setActive(i)}><span className="timeline-index">{item.current ? <span className="pulse" /> : item.period.split(' ')[0]}</span><span><b>{item.company}</b><small>{item.role}</small></span><ChevronRight size={18} /></button>)}</div><AnimatePresence mode="wait"><motion.article key={active} className="experience-detail" initial={{ opacity: 0, x: 18 }} animate={{ opacity: 1, x: 0 }} exit={{ opacity: 0, x: -12 }} transition={{ duration: .35 }}><div className="detail-top"><span>{experience[active].period}</span>{experience[active].current && <span className="current-pill">CURRENT</span>}</div><h3>{experience[active].role}</h3><p className="company-name">{experience[active].company}</p><p>{experience[active].body}</p><ul>{experience[active].bullets.map(b => <li key={b}><Check size={15} />{b}</li>)}</ul></motion.article></AnimatePresence></div></section>; }

function Pipeline() { const stages = [['01', 'Data', 'Raw language, images, voice, and behavioural context become the material an AI system can learn from.'], ['02', 'Annotation', 'I add structure through labels, grounding, reference expressions, and precise project guidelines.'], ['03', 'Evaluation', 'Outputs are checked for accuracy, relevance, consistency, and the quality of the answer itself.'], ['04', 'Human feedback', 'Structured judgement turns a subjective response into a clear training signal.'], ['05', 'Quality assurance', 'Standards, benchmarks, AHT, and reporting keep the pipeline dependable at scale.'], ['06', 'Better AI', 'The result is training data and feedback that support more useful, grounded systems.']]; return <section className="pipeline-section"><div className="page-width"><Reveal><div className="pipeline-head"><div><div className="eyebrow"><span className="eyebrow-index">03 /</span> THE WORKFLOW</div><h2>How I help<br /><em>train AI.</em></h2></div><p>Every task is a small act of translation: turning human intent, context, and judgement into signal a model can use.</p></div></Reveal><div className="pipeline"><div className="pipeline-line" />{stages.map(([num, title, desc], i) => <Reveal delay={i * .06} key={title}><article className="pipeline-stage"><span className="stage-num">{num}</span><div className="stage-icon">{i === 0 ? <Network /> : i === 1 ? <CircleDot /> : i === 2 ? <BrainCircuit /> : i === 3 ? <Sparkles /> : i === 4 ? <ShieldCheck /> : <Zap />}</div><h3>{title}</h3><p>{desc}</p></article></Reveal>)}</div></div></section>; }

function Skills() { const [selected, setSelected] = useState('AI & Machine Learning'); return <section className="skills section page-width" id="skills"><Reveal><SectionIntro eyebrow="04 / CAPABILITIES" title={'The craft is in the <em>details.</em>'} copy="A focused toolkit built around careful observation, structured thinking, and the discipline to follow a signal all the way through." /></Reveal><div className="skills-layout"><div className="skill-tabs">{Object.keys(skills).map((key, i) => <button className={selected === key ? 'selected' : ''} key={key} onClick={() => setSelected(key)}><span>0{i + 1}</span>{key}<ChevronRight size={15} /></button>)}</div><motion.div className="skill-cloud" layout key={selected}>{skills[selected].map((skill, i) => <motion.span initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: i * .035 }} key={skill} className="skill-chip">{skill}</motion.span>)}</motion.div></div></section>; }

function ResearchVisual({ accent, id }) { return <div className={`research-visual visual-${accent}`}><div className="visual-grid" />{id === '01' ? <><div className="visual-shield"><ShieldCheck /></div><div className="threat-path path-1" /><div className="threat-path path-2" /><span className="visual-code">0110 / 1001 / 1100</span></> : id === '02' ? <><div className="scan-card"><div /><div /><div /></div><span className="scan-line" /><span className="scan-label">DIAGNOSTIC / SIGNAL</span></> : id === '03' ? <><div className="news-card"><span>CLAIM</span><b>context</b><small>verified / uncertain</small></div><div className="news-pulse" /></> : id === '04' ? <><div className="climate-orbit orbit-a" /><div className="climate-orbit orbit-b" /><div className="climate-core" /></> : <><div className="gen-node n1" /><div className="gen-node n2" /><div className="gen-node n3" /><div className="gen-node n4" /><div className="gen-line l1" /><div className="gen-line l2" /><div className="gen-line l3" /><span className="visual-code">TEXT → IMAGE → REASONING</span></>}</div>; }

function ResearchCard({ item, onOpen }) { return <motion.article className={`research-card accent-${item.accent}`} whileHover={{ y: -7 }} transition={{ duration: .25 }}><ResearchVisual accent={item.accent} id={item.id} /><div className="research-card-body"><div className="research-meta"><span>{item.id}</span><span>{item.date}</span></div><h3>{item.title}</h3><div className="research-type">{item.type}</div><p>{item.short}</p><div className="tag-row">{item.tags.map(tag => <span key={tag}>{tag}</span>)}</div><div className="card-links"><button onClick={() => onOpen(item)}>View research <ArrowUpRight size={15} /></button><a href={item.pdf} download>Download PDF <Download size={14} /></a></div></div></motion.article>; }

function Research({ onOpen }) { return <section className="research section page-width" id="research"><Reveal><div className="research-header"><SectionIntro eyebrow="05 / RESEARCH LAB" title={'Independent ideas,<br /><em>carefully examined.</em>'} copy="Five independent works spanning cybersecurity, healthcare, misinformation, climate, and the evolution of generative AI. Topic visuals are conceptual interpretations; each original source document remains available to download." /><div className="research-count"><strong>05</strong><span>independent<br />research works</span><b>2022 — 2025</b></div></div></Reveal><div className="research-grid">{research.map((item, i) => <Reveal delay={i * .07} key={item.id}><ResearchCard item={item} onOpen={onOpen} /></Reveal>)}</div></section>; }

function Projects() { return <section className="projects section page-width" id="projects"><Reveal><SectionIntro eyebrow="06 / EXPERIMENTS" title={'Building on the <em>side.</em>'} copy="Self-initiated web application work using HTML, CSS, JavaScript, and API integrations. The projects are a quiet counterpoint to my AI evaluation practice: small systems, built end to end." /></Reveal><div className="project-slate"><div className="project-slate-top"><span>WEB APPLICATION DEVELOPMENT</span><span>2022 — 2024</span></div><div className="project-slate-main"><div className="project-mark"><span /><span /><span /></div><div><h3>Interactive web experiments</h3><p>Built and deployed interactive applications with browser-native technologies and API integrations. Detailed project links are intentionally left open for the next iteration.</p></div><span className="project-status">DETAILS AVAILABLE ON REQUEST</span></div></div><div className="supporting-work"><span>SUPPORTING EXPERIENCE</span><div><b>Logo & Digital Design Creator</b><small>Freelance · 2022 — 2023</small></div><div><b>Digital Marketing Specialist</b><small>Freelance · 2022 — 2023</small></div></div></section>; }

function Education() { return <section className="education section page-width"><Reveal><SectionIntro eyebrow="07 / FOUNDATION" title={'Grounded in <em>curiosity.</em>'} copy="A concise academic and language foundation, presented exactly as documented in the resume." /></Reveal><div className="education-grid"><article><span>EDUCATION</span><h3>Higher Secondary Certificate (HSC) — Science</h3><b>78.50%</b><small>2020 — 2022</small><div className="edu-rule" /><h3>Secondary School Certificate (SSC)</h3><b>85.20%</b><small>2020</small></article><article className="ielts-card"><span>IELTS ACADEMIC</span><div className="band"><strong>7.5</strong><small>Overall Band</small></div><p>CEFR C1</p><div className="score-list"><span>Listening <b>7.5</b></span><span>Reading <b>8.0</b></span><span>Writing <b>6.5</b></span><span>Speaking <b>7.0</b></span></div><small>September 2025 · IDP</small></article></div></section>; }

function Contact() { return <section className="contact section page-width" id="contact"><Reveal><div className="contact-card"><div className="contact-orbit" /><div className="eyebrow"><span className="status-dot" /> AVAILABLE FOR THE NEXT SIGNAL</div><h2>Let’s build<br /><em>better AI.</em></h2><p>For thoughtful conversations about training data, evaluation, research, or an opportunity to contribute, reach out directly.</p><div className="contact-actions"><a className="button button-primary" href="mailto:durgeshunde@gmail.com">Send an email <Mail size={16} /></a><a className="button button-ghost" href={resumeHref} download="Durgesh-Unde-Resume.pdf">Download resume <Download size={16} /></a></div><div className="contact-details"><a href="mailto:durgeshunde@gmail.com"><Mail size={16} /> durgeshunde@gmail.com</a><a href="tel:+919322323097"><span className="phone-icon">+</span> +91 93223 23097</a><span><span className="pin-icon">⌖</span> Shrirampur, Maharashtra</span></div><div className="social-placeholders"><span>GitHub <small>add profile URL</small></span><span>LinkedIn <small>add profile URL</small></span></div></div></Reveal></section>; }

function ResearchModal({ item, onClose }) { useEffect(() => { const fn = (e) => e.key === 'Escape' && onClose(); document.body.style.overflow = 'hidden'; window.addEventListener('keydown', fn); return () => { document.body.style.overflow = ''; window.removeEventListener('keydown', fn); }; }, [onClose]); return <motion.div className="modal-backdrop" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} onMouseDown={(e) => e.target === e.currentTarget && onClose()}><motion.div className="research-modal" initial={{ opacity: 0, y: 30, scale: .98 }} animate={{ opacity: 1, y: 0, scale: 1 }} exit={{ opacity: 0, y: 20, scale: .98 }} transition={{ duration: .35, ease: [0.16, 1, .3, 1] }} role="dialog" aria-modal="true" aria-labelledby="modal-title"><div className="modal-top"><span>RESEARCH LAB / {item.id}</span><button onClick={onClose} aria-label="Close research details"><X size={20} /></button></div><div className="modal-hero"><ResearchVisual accent={item.accent} id={item.id} /><div><div className="research-meta"><span>{item.date}</span><span>{item.type}</span></div><h2 id="modal-title">{item.title}</h2><div className="tag-row">{item.tags.map(tag => <span key={tag}>{tag}</span>)}</div></div></div><div className="modal-grid"><div><span className="modal-label">OVERVIEW</span><p>{item.short}</p><span className="modal-label">RESEARCH QUESTION</span><p>{item.question}</p><span className="modal-label">APPROACH</span><p>{item.method}</p></div><div><span className="modal-label">OBJECTIVES</span><ul className="modal-list">{item.objectives.map(o => <li key={o}><Check size={14} />{o}</li>)}</ul><span className="modal-label">KEY FINDING</span><p>{item.findings}</p><span className="modal-label">TAKEAWAY</span><p>{item.takeaway}</p></div></div><div className="modal-footer"><span>Original document · download unchanged</span><a className="button button-primary" href={item.pdf} download>Download full research paper <Download size={16} /></a></div></motion.div></motion.div>; }

function App() { const [modal, setModal] = useState(null); const navigate = (id) => document.getElementById(id)?.scrollIntoView({ behavior: 'smooth' }); useEffect(() => { document.documentElement.style.scrollBehavior = 'smooth'; return () => { document.documentElement.style.scrollBehavior = ''; }; }, []); return <><Header onNavigate={navigate} /><main><Hero onNavigate={navigate} /><About /><Experience /><Pipeline /><Skills /><Research onOpen={setModal} /><Projects /><Education /><Contact /></main><footer><div className="page-width footer-inner"><a className="brand" href="#top"><Mark /><span>DURGESH<br /><em>UNDE</em></span></a><span>AI Training & Evaluation · Data Annotation · AI Model Evaluation</span><span>© {new Date().getFullYear()} Durgesh Unde</span></div></footer><AnimatePresence>{modal && <ResearchModal item={modal} onClose={() => setModal(null)} />}</AnimatePresence></>; }

createRoot(document.getElementById('root')).render(<App />);
